### ISSUE TITLE
How does this compare to Beast?

### ISSUE THREAD

**Issue by vinniefalco** [pdumais/DumaisLib#1]
How does this compare to Beast, which offers WebSocket and HTTP implementations?
http://vinniefalco.github.io/

**Comment by pdumais** [comment]
Hi, I'm not sure, I've never seen beast before.
I developed this library mostly to suit my needs. One of them was to have no other depencies than stl.
Also, I wanted as less lines of code as possible when it comes to use the lib. At the cost of having limited features probably. Performance-wise, I can't say. I have no numbers.

I never tried to compare it to other libs since the primary reason I did it was to have fun. Even if the wheel already exist, it's fun to build one and show it to others who might also want to build one :)

**Comment by vinniefalco** [comment]
"Even if the wheel already exist, it's fun to build one and show it to others who might also want to build one :)"

Ain't that the truth!!
